name: mcp-rag
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: mcp-rag-qdrant
    ports:
      - "${QDRANT_SERVICE_HTTP_PORT:-6333}:${QDRANT_SERVICE_HTTP_PORT:-6333}"
      - "${QDRANT_SERVICE_GRPC_PORT:-6334}:${QDRANT_SERVICE_GRPC_PORT:-6334}"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=${QDRANT_SERVICE_HTTP_PORT:-6333}
      - QDRANT__SERVICE__GRPC_PORT=${QDRANT_SERVICE_GRPC_PORT:-6334}
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "timeout 3 bash -c '</dev/tcp/localhost/6333' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  mcp-rag-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mcp-rag-server
    ports:
      - "${FASTMCP_PORT:-8001}:${FASTMCP_PORT:-8001}"
    environment:
      # Gemini API Configuration
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.0-flash-exp}
      - GEMINI_EMBEDDING_MODEL=${GEMINI_EMBEDDING_MODEL:-text-embedding-004}
      - GEMINI_MAX_TOKENS=${GEMINI_MAX_TOKENS:-4096}
      - GEMINI_TEMPERATURE=${GEMINI_TEMPERATURE:-0.7}

      # Qdrant Configuration
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME:-documents}
      - QDRANT_COLLECTION_PREFIX=${QDRANT_COLLECTION_PREFIX:-}
      - QDRANT_VECTOR_SIZE=${QDRANT_VECTOR_SIZE:-768}
      - QDRANT_DISTANCE_METRIC=${QDRANT_DISTANCE_METRIC:-Cosine}

      # Mem0 Configuration
      - MEM0_SELF_HOSTED=${MEM0_SELF_HOSTED:-true}
      - MEM0_LOCAL_STORAGE_PATH=${MEM0_LOCAL_STORAGE_PATH:-/app/mem0_data}
      - MEM0_PROJECT_NAMESPACE=${MEM0_PROJECT_NAMESPACE:-}
      - MEM0_DEFAULT_USER_ID=${MEM0_DEFAULT_USER_ID:-default}
      - MEM0_MEMORY_SIZE=${MEM0_MEMORY_SIZE:-1000}
      - MEM0_RELEVANCE_THRESHOLD=${MEM0_RELEVANCE_THRESHOLD:-0.7}
      - MEM0_MAX_TOKENS_PER_MEMORY=${MEM0_MAX_TOKENS_PER_MEMORY:-1000}
      - MEM0_USE_SEMANTIC_SEARCH=${MEM0_USE_SEMANTIC_SEARCH:-true}
      - MEM0_SEMANTIC_SEARCH_WEIGHT=${MEM0_SEMANTIC_SEARCH_WEIGHT:-0.7}
      - MEM0_KEYWORD_SEARCH_WEIGHT=${MEM0_KEYWORD_SEARCH_WEIGHT:-0.3}
      - MEM0_RECENCY_WEIGHT=${MEM0_RECENCY_WEIGHT:-0.1}
      - MEM0_MAX_MEMORY_CONTEXT_LENGTH=${MEM0_MAX_MEMORY_CONTEXT_LENGTH:-2000}
      - MEM0_ENABLE_MEMORY_SUMMARIZATION=${MEM0_ENABLE_MEMORY_SUMMARIZATION:-true}

      # MCP Server Configuration
      - MCP_SERVER_HOST=${MCP_SERVER_HOST:-localhost}
      - MCP_SERVER_PORT=${MCP_SERVER_PORT:-8000}
      - FASTMCP_HOST=${FASTMCP_HOST:-0.0.0.0}
      - FASTMCP_PORT=${FASTMCP_PORT:-8001}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
      - MCP_SESSION_TIMEOUT_HOURS=${MCP_SESSION_TIMEOUT_HOURS:-24}
      - MCP_MAX_SESSIONS_PER_USER=${MCP_MAX_SESSIONS_PER_USER:-10}
      - MCP_SESSION_CLEANUP_INTERVAL_MINUTES=${MCP_SESSION_CLEANUP_INTERVAL_MINUTES:-5}
      - MCP_ENABLE_SESSION_TRACKING=${MCP_ENABLE_SESSION_TRACKING:-true}
    volumes:
      - mem0_data:/app/mem0_data
    depends_on:
      qdrant:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/mcp/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_data:
  mem0_data:
